//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarxistReader {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class WorkViewerSettings : global::System.Configuration.ApplicationSettingsBase {
		
		private static WorkViewerSettings defaultInstance = ((WorkViewerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WorkViewerSettings())));
		
		public static WorkViewerSettings Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
		public global::System.Drawing.Point Location {
			get {
				return ((global::System.Drawing.Point)(this["Location"]));
			}
			set {
				this["Location"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool Maximised {
			get {
				return ((bool)(this["Maximised"]));
			}
			set {
				this["Maximised"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("640, 500")]
		public global::System.Drawing.Size Size {
			get {
				return ((global::System.Drawing.Size)(this["Size"]));
			}
			set {
				this["Size"] = value;
			}
		}
	}
}
